[project]
name = "hqu-school-mcp-server"
version = "0.1.0"
description = "MCP for HQUer querying data"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.6.0",
]